version: '3'

services:
  nginx:
    hostname: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/frontend.conf:/etc/nginx/sites-enabled/frontend.conf
      - ./nginx/sites-enabled/backend.conf:/etc/nginx/sites-enabled/backend.conf
    ports:
      - ${APP_PORT}:80
      - "8081:81"
    depends_on:
      - frontend
      - backend
  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
      - ./frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "npm", "run", "start:dev" ]
    ports:
      - "81:3000"
    volumes:
      - ./backend:/backend
      - backend_node_modules:/backend/node_modules
      - ./backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_node_modules:
    driver: local
  backend_node_modules:
    driver: local
