version: '3'

services:
  nginx:
    hostname: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/frontend.conf:/etc/nginx/sites-enabled/frontend.conf
    ports:
      - ${APP_PORT}:80
      - 8081:81
    depends_on:
      - frontend
  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
      - ./frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_node_modules:
    driver: local
